// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn_JhxCz-MwJ2My8KORZdET-7VVg5ul88',
    appId: '1:308853033791:web:54df939a54b2f77766618a',
    messagingSenderId: '308853033791',
    projectId: 'petshop-5ee8b',
    authDomain: 'petshop-5ee8b.firebaseapp.com',
    storageBucket: 'petshop-5ee8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1euHJN1fmDz_Yzd1oOlZs2PM0yqJb7m4',
    appId: '1:308853033791:android:2ab19643b9d2182a66618a',
    messagingSenderId: '308853033791',
    projectId: 'petshop-5ee8b',
    storageBucket: 'petshop-5ee8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvq8Y6cFh5iq8VtanOR5PAI31u7ydldO0',
    appId: '1:308853033791:ios:37807921a9d063c566618a',
    messagingSenderId: '308853033791',
    projectId: 'petshop-5ee8b',
    storageBucket: 'petshop-5ee8b.appspot.com',
    iosBundleId: 'com.example.testt',
  );
}
